[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "5UQSxfCQmJkr4XDW4sdPbxktbUS5vGzzCTq9Mm7g7k8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/matuu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
